In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[725, 5760, 6422, 2904],
 [725, 5760, 6422, 6071],
 [725, 7618, 6422, 2658],
 [5302, 5148, 4643, 2193, 1045],
 [5302, 5148, 4643, 2193, 6742],
 [2297, 725, 7692, 6422, 5707],
 [2383, 8760, 2597, 2193]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  725 5760 6422 2904]
 [   0    0    0    0  725 5760 6422 6071]
 [   0    0    0    0  725 7618 6422 2658]
 [   0    0    0 5302 5148 4643 2193 1045]
 [   0    0    0 5302 5148 4643 2193 6742]
 [   0    0    0 2297  725 7692 6422 5707]
 [   0    0    0    0 2383 8760 2597 2193]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Sanjana D\Downloads\simple_rnn_imdb (1)\word\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[[-0.03557657, -0.0107609 ,  0.01130271, -0.00515249,
         -0.00779723, -0.03746655,  0.0378657 ,  0.01683204,
          0.02837277,  0.00920362],
        [-0.03557657, -0.0107609 ,  0.01130271, -0.00515249,
         -0.00779723, -0.03746655,  0.0378657 ,  0.01683204,
          0.02837277,  0.00920362],
        [-0.03557657, -0.0107609 ,  0.01130271, -0.00515249,
         -0.00779723, -0.03746655,  0.0378657 ,  0.01683204,
          0.02837277,  0.00920362],
        [-0.03557657, -0.0107609 ,  0.01130271, -0.00515249,
         -0.00779723, -0.03746655,  0.0378657 ,  0.01683204,
          0.02837277,  0.00920362],
        [ 0.04521197, -0.04471201, -0.00553267, -0.04318743,
          0.00858159, -0.01030462, -0.0380098 , -0.03191721,
         -0.02763823, -0.04563969],
        [ 0.03219861, -0.03147464, -0.0165414 , -0.00941042,
         -0.04919004, -0.04552771, -0.02747402, -0.00887041,
          0.00155444,  0.0435296 ],
        [-0.00551516,  0.00092917, -0.01838044,  0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,  725, 5760, 6422, 2904])

In [26]:
embedded_docs[0].shape

(8,)

In [27]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step


array([[[-0.03557657, -0.0107609 ,  0.01130271, -0.00515249,
         -0.00779723, -0.03746655,  0.0378657 ,  0.01683204,
          0.02837277,  0.00920362],
        [-0.03557657, -0.0107609 ,  0.01130271, -0.00515249,
         -0.00779723, -0.03746655,  0.0378657 ,  0.01683204,
          0.02837277,  0.00920362],
        [-0.03557657, -0.0107609 ,  0.01130271, -0.00515249,
         -0.00779723, -0.03746655,  0.0378657 ,  0.01683204,
          0.02837277,  0.00920362],
        [-0.03557657, -0.0107609 ,  0.01130271, -0.00515249,
         -0.00779723, -0.03746655,  0.0378657 ,  0.01683204,
          0.02837277,  0.00920362],
        [ 0.04521197, -0.04471201, -0.00553267, -0.04318743,
          0.00858159, -0.01030462, -0.0380098 , -0.03191721,
         -0.02763823, -0.04563969],
        [ 0.03219861, -0.03147464, -0.0165414 , -0.00941042,
         -0.04919004, -0.04552771, -0.02747402, -0.00887041,
          0.00155444,  0.0435296 ],
        [-0.00551516,  0.00092917, -0.01838044,  0.0